### ISSUE TITLE
JSAPI widget parameters

### ISSUE THREAD

**Issue by avezina** [Esri/solutions-widget-utility-network-trace#107]
### **Priority - High**
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/109 - @previnWong to ask William who is in charge of getting the current version to give trace
- [x] #99 to Show/hide the list of selected features results: boolean
- [x] https://github.com/Esri/solutions-widget-utility-network-trace/issues/104
- [x] https://github.com/Esri/solutions-widget-utility-network-trace/issues/110
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/108

___
### **Priority - Medium**
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/77
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/111
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/117
- [x] https://github.com/Esri/solutions-widget-utility-network-trace/issues/112
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/79
- [ ] Parameter to override Icons/markers for flags to https://github.com/Esri/solutions-widget-utility-network-trace/issues/68
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/100
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/79

___
### **Priority - Low**
- [ ] #115
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/116
- [ ] Option to allow Export results? Should this be part of JSAPI?
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/114
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/113
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/118
- [ ] https://github.com/Esri/solutions-widget-utility-network-trace/issues/124

**Comment by avezina** [comment]
Pushing this issue to 4.23 for further implementation
